### ISSUE TITLE
[Anon] Bug report: Galactic_Republic.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/star-wars-legion#11]
**File:** Galactic_Republic.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** When adding personnel "Fives" or "Echo" to a unit, they are not supposed to increase the courage of the unit. The physical upgrade card has a green "2" indicating that the specific mini can take 2 wounds instead of one like the rest of the unit.

**Comment by XWingDrLucky** [comment]
Only Fives does this presently.  Fives has card text that reads "Your courage is increased by 1."

The file is correct.
