### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by JoshWeller** [BSData/star-wars-legion#20]
Hi, I would like to help contribute to the Star Wars Legion repo.

**Comment by DrTobogganMD** [comment]
Hello, @JoshWeller . Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

Also, join the data author community over at discord!

[![Chat on Discord](https://img.shields.io/discord/558412685981777922.svg?logo=discord&style=popout-square)](https://discord.gg/KqPVhds)

Cheers!

[invitation]: https://github.com/BSData/star-wars-legion/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide
