### ISSUE TITLE
Grand Army Ranks

### ISSUE THREAD

**Issue by LachrimallusExterminator** [BSData/star-wars-legion#21]
The Heavy rank allows up to 3 selections instead of 4. If this has been FAQed somewhere, please let me know. It does not match the rules I downloaded from FFG. This happens in at least Empire and Republic, though may happen for all factions.

iOS 14.7.1
BS Version 2.03.15
Star Wars Legion 1.9.4
Dropbox No

![9F26FAE4-0A56-4ED7-843A-38321BED5E6B](https://user-images.githubusercontent.com/84422145/131579265-f52756a1-1b84-44d4-967d-0b089f193c26.png)
![61C097B8-C297-40C9-B6ED-A4DE5BE4A40A](https://user-images.githubusercontent.com/84422145/131579268-3e295f23-9546-48ff-afad-1fc210d0ccd7.png)

**Comment by JoshWeller** [comment]
Hi LachrimallusExterminator,

Thank you for letting me know. Looks like there were a few incorrect limits for Grand Army. I have corrected them in my current working version, I hope to have it uploaded later today. From there, it can take 12 hours to be available as an update in the app.

JoshWeller

**Comment by JoshWeller** [comment]
Grand Army rank requirements corrected in the latest update.
