### ISSUE TITLE
Imperial Hammers Elite Armor Pilot should give a surge to hit. It gives a surge to crit.

### ISSUE THREAD

**Issue by CyberClaw** [BSData/star-wars-legion#3]
The card text is correct, but when equipped for example in the AT ST, it gives a surge to crit in the AT ST Attack section.

**Comment by XWingDrLucky** [comment]
Verified. I'll fix this tonight. Thanks for reporting the error.

**Comment by XWingDrLucky** [comment]
Issue is fixed in the latest commit.  It will go live in the next release.
